#%RAML 1.0 Library
usage: |
  Common resources for drivers services: ilsos-drivers-sapi

types:

  driverInformation:
    type: object
    description: Driver Information
    displayName: Driver Information
    additionalProperties: false
    properties:
      dl:
        required: false
        description: Drivers license number
        type: string
        maxLength: 12
        pattern: ^[A-Z]{1}[0-9]{11}$
        example: Z14247504133
      stateId:
        required: false
        description: Identification number
        type: string
        maxLength: 12
        pattern: ^[0-9]{12}$
        example: '999123456700'
      dateOfBirth:
        required: true
        description: Date of birth
        type: date-only
        example: 1970-01-01
      ssnLast4:
        required: true
        description: SSN last 4 digits
        type: string
        pattern: ^[0-9]{4}$
        maxLength: 4
        example: '2345'
      street:
          type: string
          required: true
          example: 1202 Hidden Ridge
          minLength: 1
          maxLength: 46
          description: The number of a building along with the name of the road or street on which it is located.
      city:
        type: string
        required: true
        example: Irving
        minLength: 1
        maxLength: 20
        description: This is the city name of the address.
      state:
        type: string
        enum: [AA,AE,AL,AK,AP,AS,AZ,AR,CA,CO,CT,DE,DC,FM,FL,GA,GU,HI,ID,IL,IN,IA,KS,KY,LA,ME,MH,MD,MA,MI,MN,MS,MO,MP,MT,NE,NV,NH,NJ,NM,NY,NC,ND,OH,OK,OR,PW,PA,PR,RI,SC,SD,TN,TX,UT,VT,VI,VA,WA,WV,WI,WY]
        required: true
        example: TX
        maxLength: 2
        description: This is two-character state code of the address.
      zipCode:
        type: string
        required: true
        example: "45623"
        pattern: ^[0-9]{5}$
        maxLength: 5
        description: This is the 5-digit ZIP code.  
      countyCode:
        required: true
        description: County code
        type: string
        maxLength: 3
        example: '120'
    examples:
      driver-information:
        displayName: Basic driver information
        description: Basic driver information
        value:
          dl: P14247504133
          stateId: '999123456700'
          dateOfBirth: 1970-01-01
          ssnLast4: '2345'
          street: 3 Rodeo St
          city: San Jose
          state: IL
          zipCode: '62000'
          countyCode: '234'


  addressChangeType:
    type: driverInformation
    description: Address change
    displayName: Address change
    additionalProperties: false
    properties:
      ipaddress:
        required: false
        description: User IP address
        type: string
        maxLength: 15
        example: "123.122.233.102"
      department:
        required: false
        description: department
        type: string
        enum: [DS,VS]
        example: DS
      dlIssueDate:
        required: false
        description: Drivers license issue date
        type: date-only
        example: 2026-10-01
      stateIdIssueDate:
        required: false
        description: Identification issue date
        type: date-only
        example: 2026-10-01
      userAcceptedAddreesValidation:
        required: false
        description: The user acepted the address validation from USPS service
        type: boolean
        example: true
      tvdl:
        required: false
        description: Temporary visitor drivers license holder
        type: string
        maxLength: 12
        example: P14247504999
    examples:
      address-update:
        displayName: Address Change Example
        description: Next is the example when the object is used for the Driver Address Change process
        value:
          ipaddress: "123.122.233.102"
          department: DS
          dl: P14247504133
          dlIssueDate: 2026-10-01
          stateId: '999123456700'
          stateIdIssueDate: 2026-10-01
          dateOfBirth: 1970-01-01
          ssnLast4: '2345'
          tvdl: P14247504999
          street: 3 Rodeo St
          city: San Jose
          state: IL
          zipCode: '62999'
          countyCode: '234'
          userAcceptedAddreesValidation: true


traits:
  idVerificationQueryParameters:
    queryParameters:
      dl: 
        description: Driver's license number
        required: false
        example: "P14247504133"
        type: string
      stateId:
        description: Identification number
        required: false
        example: 999123456700
        type: number
      ssnLast4:
        description: Last 4 digits of SSN for verification
        required: true
        example: 0347
        type: number